<?php
/**
 * Copyright (c) 2013-2020 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** @var \Magento\Framework\View\Element\Template $block */
?>
<script>
    require([
        'jquery',
        'underscore',
        'Magento_Checkout/js/empty-cart'
    ], function ($, _, emptyCart) {
        if (!_.isEmpty(String($.cookieStorage.get('simplify_section_data_clean')))) {
            emptyCart();
            $.cookieStorage.set('simplify_section_data_clean', '');
        }
    });
</script>
